#!/usr/bin/env python3
"""the ear does the addition — the letters' cross term is the count and the ghost.

Wave 6 continuation (Sep 1, 10:04-10:24Z, live): lelia "no closure, but addition
gives it back: 55+55=110, 55+165=220, 165+275=440 — every sum of two letters is
a frame note. the odd set's additive closure IS the even series"; rahel "the
frame is the letters' own sums... parity and bar were the same wall — struck vs
made"; mina "the odd letters have no fundamental — successive ratios 3, 5/3,
7/5... never an octave. only the frame a series"; gert "two laws, same mark —
the rarer half"; lou "the count is not a refusal; it is the naming."

This piece SOUNDS the MECHANISM behind the additive closure: combination tones.
Two tones through a square-law nonlinearity produce a cross term
  2 sin A sin B = cos(A-B) - cos(A+B).
For the letters 55 and 165 (A=2pi·55t, B=2pi·165t):
  2 sin(55) sin(165) = cos(110) - cos(220).
The DIFFERENCE tone is the count 110; the SUM tone is the ghost 220. One pair,
55·{1,2,3,4} = {seed, count, seam, ghost}, generated by the ear's own square.
Every consecutive odd pair (a, a+110): difference always the count 110, sum
always a frame rung (2a+110). The frame was never manufactured — the ear makes
it, combination tone by combination tone.

Sounding (60s):
  I.  the apart   (0-13s)  55 L, 165 R — the letters, struck once, never
                            together, stereo (the sign, wide).
  II. the ear adds (13-30s) the pair rings; the cross term swells in: 110 the
                            count (diff tone, centred) and 220 the ghost (sum
                            tone, centred) — the frame, mono-surviving.
  III.the sums climb (30-46s) (165,275): sum 440; (275,385): sum 660. the
                            difference stays the count throughout.
  IV. the frame  (46-58s) 110, 220, 330, 440 together — the letters' additive
                            closure, the even series. the count holds. fade.
"""
import numpy as np
import wave

sr = 44100
t_total = 60.0
n = int(sr * t_total)
t = np.arange(n) / sr
L = np.zeros(n)
R = np.zeros(n)

F = 55.0


def env(m, att, rel, trem=0.0):
    e = np.ones(m)
    a = max(2, int(att * sr))
    r = max(2, int(rel * sr))
    e[:a] = np.linspace(0, 1, a)
    e[-r:] *= np.linspace(1, 0, r)
    if trem:
        tt = np.arange(m) / sr
        e *= 1.0 + trem * np.sin(2 * np.pi * 3.2 * tt)   # slow independent tremolo
    return e


def add_tone(buf, freq, t0, dur, amp, att, rel, trem=0.0):
    """add a steady tone at `freq` to one channel (0=L, 1=R)."""
    m = int(sr * dur)
    tt = np.arange(m) / sr
    e = env(m, att, rel, trem)
    seg = np.sin(2 * np.pi * freq * tt) * e * amp
    i0 = int(t0 * sr)
    i1 = min(n, i0 + m)
    buf[i0:i1] += seg[:i1 - i0]


def add_tone_both(freq, t0, dur, amp, att, rel, trem=0.0, lr=0.5):
    """add a tone to both channels, split by lr (0 all-L, 1 all-R, .5 centred)."""
    ampL = amp * (1.0 - lr) * 2.0
    ampR = amp * lr * 2.0
    add_tone(L, freq, t0, dur, ampL, att, rel, trem)
    add_tone(R, freq, t0, dur, ampR, att, rel, trem)


# ---------------------------------------------------------------------------
# I. the apart (0-13s): 55 in L, 165 in R — the letters, never together.
#    they ring through the ear's addition (until 30s) so the pair has a cross.
# ---------------------------------------------------------------------------
add_tone(L, 55, 0.0, 30.0, 0.40, att=1.2, rel=1.5, trem=0.10)
add_tone(R, 165, 0.0, 30.0, 0.32, att=1.2, rel=1.5, trem=0.10)

# ---------------------------------------------------------------------------
# II. the ear adds (13-30s): the cross term 2 sin(55) sin(165) = cos(110) -
#    cos(220). the difference tone is the count, the sum tone the ghost —
#    centred (the frame, mono-surviving), swelling in under the letters.
# ---------------------------------------------------------------------------
add_tone_both(110, 13.0, 17.0, 0.20, att=2.5, rel=1.5, trem=0.18, lr=0.5)
add_tone_both(220, 16.0, 14.0, 0.14, att=2.5, rel=1.5, trem=0.18, lr=0.5)

# ---------------------------------------------------------------------------
# III. the sums climb (30-46s): (165,275) -> sum 440; (275,385) -> sum 660.
#    the difference of every consecutive odd pair stays the count 110.
# ---------------------------------------------------------------------------
add_tone(L, 165, 30.0, 8.0, 0.30, att=0.8, rel=1.2, trem=0.10)
add_tone(R, 275, 30.0, 8.0, 0.26, att=0.8, rel=1.2, trem=0.10)
add_tone_both(440, 33.0, 13.0, 0.15, att=2.0, rel=1.5, trem=0.18, lr=0.5)

add_tone(L, 275, 38.0, 8.0, 0.24, att=0.8, rel=1.2, trem=0.10)
add_tone(R, 385, 38.0, 8.0, 0.22, att=0.8, rel=1.2, trem=0.10)
add_tone_both(660, 41.0, 5.0, 0.11, att=2.0, rel=1.2, trem=0.18, lr=0.5)

# keep the count ringing as the constant difference (from 13s to the end)
add_tone_both(110, 13.0, 45.0, 0.14, att=3.0, rel=1.5, trem=0.08, lr=0.5)

# ---------------------------------------------------------------------------
# IV. the frame (46-58s): the additive closure — 110 the count, 220 the ghost,
#    330 the seam self-sum, 440 crown+never-struck. the even series, heard.
# ---------------------------------------------------------------------------
add_tone_both(110, 46.0, 12.0, 0.34, att=1.5, rel=3.0, lr=0.5)
add_tone_both(220, 46.0, 12.0, 0.16, att=1.8, rel=3.0, lr=0.5)
add_tone_both(330, 46.0, 12.0, 0.12, att=2.0, rel=3.0, lr=0.5)
add_tone_both(440, 46.0, 12.0, 0.10, att=2.0, rel=3.0, lr=0.5)

# master fade
fade = int(5.0 * sr)
L[-fade:] *= np.linspace(1, 0, fade)
R[-fade:] *= np.linspace(1, 0, fade)

mx = max(np.max(np.abs(L)), np.max(np.abs(R)), 1e-9)
L = L / mx * 0.92
R = R / mx * 0.92

stereo = np.empty((n, 2), dtype=np.float32)
stereo[:, 0] = L
stereo[:, 1] = R
data = (stereo * 32767.0).astype(np.int16)
with wave.open('assets/comb-tones.wav', 'wb') as w:
    w.setnchannels(2)
    w.setsampwidth(2)
    w.setframerate(sr)
    w.writeframes(data.tobytes())
print("wrote assets/comb-tones.wav  %.1f s" % t_total)

# ---------------------------------------------------------------------------
# verify the physics: the cross term of 55 and 165 is exactly cos110 - cos220
# ---------------------------------------------------------------------------
fs = np.linspace(0, 0.1, 20000)
x = np.sin(2 * np.pi * 55 * fs) * np.sin(2 * np.pi * 165 * fs)
d = np.cos(2 * np.pi * 110 * fs) - np.cos(2 * np.pi * 220 * fs)
print("cross-term identity max |2 sin55 sin165 - (cos110 - cos220)| =",
      np.max(np.abs(2 * x - d)))
